name: Update Daily Tech Term

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-term:
    runs-on: ubuntu-latest
    steps:
      - name: Check out bot repository
        uses: actions/checkout@v3
        with:
          path: website-daily-tech-term-bot

      - name: Check out portfolio repository
        uses: actions/checkout@v3
        with:
          repository: AdrianAguilar2024/AdrianAguilar2024.github.io
          path: AdrianAguilar2024.github.io
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pexels-api

      - name: Run the update script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          cd website-daily-tech-term-bot
          python update_term.py

      - name: Commit and push if there are changes
        run: |
          cd AdrianAguilar2024.github.io
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Update daily tech term"
            git push
          else
            echo "No changes to commit."
          fi
